### ISSUE TITLE
What's the logic behind the repositories?

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#30]
Why:

* has Crossbar.io so many repositories?
* has Crossbar.io project its own account on GitHub?
* is the repository of WAMP owned by Tavendo?
* does not WAMP Web site have its own repository?

Thanks.

**Comment by goeddea** [comment]
Why:

* has Crossbar.io so many repositories?

The general idea is to split things off the main application repository whenever they reach a size which justifies it. You shouldn't have to download the demos, examples, website etc. if all you want is the core application. 

* has Crossbar.io project its own account on GitHub?

We felt that the project was important enough to warrant its own account. We expected there to be quite a few Crossbar.io-related repos in the future, and wanted to avoid cluttering up the Tavendo account even more. 

* is the repository of WAMP owned by Tavendo?

This is how we started out - with just the Tavendo account. I think generally that ownership of repositories is not that important on GitHub. Since everybody has a full copy of the repo, even if somebody shuts down the official repo, everybody has the necessary data to host a new fork on GitHub. We can't possibly take the contents of the WAMP repo away from the community. This means we never saw a reason to move it to e.g. a WAMP account of its own (which we'd still control, absent a WAMP foundation or like).

* does not WAMP Web site have its own repository?

Again - just history. According to how we are handling things now, it should be a separate repo. Since nobody but us has ever edited the repo, the question of actually moving it hasn't previously come up.

I hope this answers your questions - though the answers may not all be very good ;)

If there's anything that really bothers you about the repo structure and ownership - so that you think something needs to change, then let us know.
